import os

def generate_text_sprites(breeds):
    """Generate text-based animal sprites for the given breeds"""
    print("=== MCP TESTSPRITE GENERATOR ===")
    print("Generating text-based animal sprites...\n")
    
    # Create sprites directory
    sprite_dir = os.path.join(os.path.dirname(__file__), 'text_sprites')
    os.makedirs(sprite_dir, exist_ok=True)
    
    generated_count = 0
    
    for breed in breeds:
        print(f"Generating sprite for: {breed}")
        
        # Determine animal type from breed name
        animal_type = "cow"
        if "Buffalo" in breed:
            animal_type = "buffalo"
        elif "Goat" in breed:
            animal_type = "goat"
        elif "Sheep" in breed:
            animal_type = "sheep"
        
        # Generate ASCII art based on animal type
        sprite_content = generate_ascii_art(breed, animal_type)
        
        # Save to file
        filename = f"mcp_{breed.replace(' ', '_')}.txt"
        filepath = os.path.join(sprite_dir, filename)
        
        with open(filepath, 'w') as f:
            f.write(sprite_content)
        
        print(f"✓ Sprite saved to: {filepath}\n")
        generated_count += 1
    
    print("=== MCP TESTSPRITE GENERATION COMPLETE ===")
    print(f"Generated {generated_count} text sprites in {sprite_dir}\n")
    
    # Display an example
    if breeds:
        print("Example sprite content:\n")
        print(generate_ascii_art(breeds[0], "cow" if "Buffalo" not in breeds[0] else "buffalo"))
    
    return True

def generate_ascii_art(breed, animal_type):
    """Generate ASCII art for a specific animal type"""
    import random
    
    confidence = random.randint(85, 95)
    
    if animal_type == "buffalo":
        art = f"""=== {breed} ===
Confidence: {confidence}.0%


         _.--._
      .-'  _   '-. 
     /   .' '.   \\
    |   /     \\   |
    |   \\_o o_/   |
    /\\    ___    /\\
   /  '-._____.-'  \\
  /                 \\
 /                   \\
/                     \\


Generated by MCP TestSprite"""
    
    elif animal_type == "goat":
        art = f"""=== {breed} ===
Confidence: {confidence}.0%


       _))
      > *\\     _~
      `;'\\\\__-' \\_
         | )  _ \\ \\
        / / ``   w w
       w w


Generated by MCP TestSprite"""
    
    elif animal_type == "sheep":
        art = f"""=== {breed} ===
Confidence: {confidence}.0%


      _.-````'-,_
    .'  _     _  '.
   /   (o)   (o)   \\
  |                 |
  |   \\           /  |
   \\   '.       .'  /
    '.  `'-----'`  .'
      '-._____.-'


Generated by MCP TestSprite"""
    
    else:  # Default cow
        art = f"""=== {breed} ===
Confidence: {confidence}.0%


        ^__^
        (oo)\\_______
        (__)\\       )/\\/
            ||----w |
            ||     ||


Generated by MCP TestSprite"""
    
    return art

if __name__ == "__main__":
    # Test with some breeds
    test_breeds = ["Holstein Cow", "Murrah Buffalo", "Gir Cow", "Sahiwal Cow"]
    generate_text_sprites(test_breeds)